// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttmqmgiubfjibcqeycpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0bXFtZ2l1YmZqaWJjcWV5Y3BmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDA1NjcsImV4cCI6MjA2Mjk3NjU2N30.4CA-9elLDcLGJaJGvuT5pvFwEdMRFaO8G55Yhd4JLvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});